import Foundation

// LuminaGram: localization layer. A single global helper that translates the
// English UI literals the LuminaGram fork adds. Call sites wrap their existing
// English string verbatim, e.g. LuminaL10n.tr("Backup"); the current app
// language is pushed in from SharedAccountContext. Missing strings fall back to
// the English text, so an un-added language simply shows English.
//
// Pure Foundation, no other imports. Lives in TelegramUIPreferences, a low
// module every UI module already depends on, so no BUILD dependency changes are
// needed for any caller.
public enum LuminaL10n {
    private static let lock = NSLock()
    private static var current: String = "en"

    /// Set the active language. Accepts any app language code; it is normalized
    /// to one of the tables below ("zh-hans" / "zh-hant") or "en".
    public static func setCurrentLanguage(_ code: String) {
        let normalized = normalize(code)
        lock.lock()
        current = normalized
        lock.unlock()
    }

    /// Translate an English UI literal for the current language, or return the
    /// English text unchanged when there is no translation.
    public static func tr(_ s: String) -> String {
        lock.lock()
        let lang = current
        lock.unlock()
        if let table = translations[lang], let value = table[s] {
            return value
        }
        return s
    }

    /// Map an app language code to a table key. Simplified variants (hans, cn,
    /// sg, hans-raw, classic-zh-cn) -> "zh-hans"; Traditional variants (hant,
    /// tw, hk, mo, hant-raw) -> "zh-hant"; anything else -> its 2-letter prefix;
    /// empty -> "en". A bare "zh" with no region defaults to Simplified.
    private static func normalize(_ code: String) -> String {
        let lower = code.lowercased().replacingOccurrences(of: "_", with: "-")
        if lower.contains("zh") {
            // Order matters only in that hant / hans markers never co-occur.
            for marker in ["hant", "tw", "hk", "mo"] where lower.contains(marker) {
                return "zh-hant"
            }
            for marker in ["hans", "cn", "sg"] where lower.contains(marker) {
                return "zh-hans"
            }
            // "hant-raw" / "hans-raw" already matched above; a bare "zh"
            // (no region) falls through to Simplified.
            return "zh-hans"
        }
        let prefix = String(lower.prefix(2))
        return prefix.isEmpty ? "en" : prefix
    }

    private static let translations: [String: [String: String]] = [
        "zh-hans": [
            "LANGUAGES": "语言",
            "INCOMING MESSAGES": "收到的消息",
            "OUTGOING MESSAGES": "发送的消息",
            "TRANSLATE MODE": "翻译模式",
            "TRANSLATION PROVIDER": "翻译服务商",
            "TRANSLATE BEFORE SEND": "发送前翻译",
            "TONE FOR THIS CHAT": "这个对话的语气",
            "GLOSSARY": "不翻译词表",
            "IMAGE TEXT": "图片文字",
            "EXPLAIN": "解释一下",
            "VOICE-TO-TEXT": "语音转文字",
            "VOICE LANGUAGE": "语音语言",
            "REVERSE VOICE (EXPERIMENTAL)": "反向语音（实验性）",
            "MESSAGE": "消息",
            "MESSAGE TEXT": "消息文本",
            "SHORTCUT NAME": "快捷名称",
            "TAGS": "标签",
            "PRIVATE NOTE": "私密备注",
            "TEMPLATES": "模板",
            "FEATURES": "功能",
            "SCREENS": "页面",
            "STORIES": "动态",
            "DISPLAY": "显示",
            "MEDIA": "媒体",
            "PRIVACY": "隐私",
            "PRIVACY & DISGUISE": "隐私与伪装",
            "ANTI-SCAM GUARDS": "防诈骗防护",
            "TWO-STEP VERIFICATION": "两步验证",
            "ACTIVE SESSIONS": "活动会话",
            "CHAT LOCK": "对话上锁",
            "BACKUP PASSPHRASE": "备份口令",
            "Translation": "翻译",
            "Privacy": "隐私",
            "Security": "安全",
            "Tools": "工具",
            "Voice & Media": "语音与媒体",
            "LuminaGram options are stored on this device only and are never synced to Telegram.": "LuminaGram 的选项只保存在这台设备上，绝不会同步到 Telegram。",
            "These options and everything else under LuminaGram are stored on this device only.": "这些选项以及 LuminaGram 下的其他一切都只保存在这台设备上。",
            "I read": "我阅读",
            "I send": "我发送",
            "Target": "目标语言",
            "Interface language": "界面语言",
            "auto = recipient's language": "自动 = 对方语言",
            "Only Translate What I Can't Read": "只翻译我看不懂的",
            "Private Chats": "私聊",
            "Groups & Channels": "群组与频道",
            "All Chats": "所有对话",
            "Manual (per-chat toggle)": "手动（逐对话开关）",
            "Show Original + Translation": "显示原文＋译文",
            "Fold Long Originals": "折叠过长原文",
            "Base URL": "接口地址",
            "Model": "模型",
            "API key": "API 密钥",
            "DeepL Key": "DeepL 密钥",
            "LLM Key": "LLM 密钥",
            "LLM (OpenAI-compatible)": "LLM（兼容 OpenAI）",
            "Test Provider": "测试服务商",
            "The test translation failed. Check the provider's API key and settings.": "测试翻译失败。请检查服务商的 API 密钥和设置。",
            "DeepL and LLM keys are stored in the device Keychain, never synced to Telegram or LuminaGram. Base URL/Model/Prompt apply to the LLM provider only.": "DeepL 和 LLM 密钥保存在设备的钥匙串中，绝不会同步到 Telegram 或 LuminaGram。接口地址／模型／提示词仅适用于 LLM 服务商。",
            "Could not reach the configured LLM provider. Check the base URL in Translation settings.": "无法连接所配置的 LLM 服务商。请检查翻译设置中的接口地址。",
            "Translate Before Send": "发送前翻译",
            "Enabled for This Chat": "已为此对话启用",
            "Chat Translation Settings": "对话翻译设置",
            "Send Translation": "发送翻译",
            "Send Original": "发送原文",
            "Send translation?": "发送翻译？",
            "Also needs to be turned on per chat: long-press any message in that chat and choose Chat Translation Settings.": "还需在每个对话中单独开启：长按该对话中的任意消息，选择「对话翻译设置」。",
            "Also needs the global switch on: Settings → LuminaGram → Translation → Translate Before Send.": "还需在总开关处开启：设置 → LuminaGram → 翻译 → 发送前翻译。",
            "Custom": "自定义",
            "None": "无",
            "Client": "客户",
            "Colleague": "同事",
            "Friend": "朋友",
            "Family": "家人",
            "Elder": "长辈",
            "Romantic interest": "暧昧对象",
            "Only the LLM provider can carry tone. DeepL collapses it onto formal/informal where supported; Google and Telegram ignore it.": "只有 LLM 服务商能传达语气。DeepL 在支持的语言上会压缩为正式／非正式；Google 和 Telegram 会忽略语气。",
            "e.g. \"my landlord\"": "例如：我的房东",
            "Glossary": "不翻译词表",
            "iPhone, Acme Corp — one term per line or comma-separated": "iPhone、Acme Corp — 每行一个词或用逗号分隔",
            "Explain": "解释一下",
            "Explain-a-Message": "解释消息",
            "Add an LLM API key on the Translation settings page to use Explain.": "请先在翻译设置页添加 LLM API 密钥，才能使用「解释一下」。",
            "Could not get an explanation. Check your LLM provider settings and try again.": "无法获取解释。请检查你的 LLM 服务商设置后重试。",
            "Translate Image": "翻译图中文字",
            "Show \"Translate Image\" action": "显示「翻译图片」操作",
            "Uses Telegram's existing on-device Vision text recognition to translate text found in photos and screenshots, from the image viewer's menu.": "借助 Telegram 已有的设备端 Vision 文字识别，从图片查看器菜单翻译照片和截图中的文字。",
            "Auto-transcribe in translated chats": "在翻译的对话中自动转录",
            "Translate transcript automatically": "自动翻译转录文字",
            "Transcribing…": "转录中…",
            "Transcription failed.": "转录失败。",
            "No speech was recognized.": "未识别到语音。",
            "On-device transcription isn't available for this language.": "此语言暂不支持设备端转录。",
            "Speech recognition permission is required. Enable it in Settings.": "需要语音识别权限。请在系统设置中开启。",
            "Voice message isn't downloaded yet.": "语音消息尚未下载。",
            "Couldn't read this voice message.": "无法读取这条语音消息。",
            "Reverse Voice": "反向语音",
            "Enable reverse voice": "启用反向语音",
            "Send a Reverse Voice Message": "发送反向语音消息",
            "Send as Voice Message": "作为语音消息发送",
            "Message": "消息",
            "Type the message to speak…": "输入要朗读的消息…",
            "Voice message sent.": "语音消息已发送。",
            "Couldn't create the voice message.": "无法生成语音消息。",
            "en, ja, fr — one per line or comma-separated": "en、ja、fr — 每行一个或用逗号分隔",
            "BCP-47 language/voice code understood by AVSpeechSynthesisVoice.": "AVSpeechSynthesisVoice 可识别的 BCP-47 语言／语音代码。",
            "Spoken on-device with AVSpeechSynthesizer and sent as a real voice message. No cloud TTS, no voice cloning.": "使用 AVSpeechSynthesizer 在设备上朗读，并作为真正的语音消息发送。不使用云端 TTS，不做语音克隆。",
            "e.g. en-US, zh-CN (leave empty to auto-detect)": "例如 en-US、zh-CN（留空自动检测）",
            "Auto-pause video in background": "应用退到后台时暂停视频",
            "Keep original filename on save": "保存时保留原始文件名",
            "Strip Photo Metadata": "移除照片元数据",
            "Save to \"LuminaGram\" album": "保存到「LuminaGram」相册",
            "Sticker Size": "贴纸大小",
            "Choose how large stickers render in chats.": "调整贴纸在聊天中的显示大小。",
            "Small (75%)": "小（75%）",
            "Default (100%)": "默认（100%）",
            "Large (125%)": "大（125%）",
            "Precise Counts": "精确计数",
            "No 1.2K / 3.4M rounding": "不使用 1.2K／3.4M 缩写",
            "Seconds in Timestamps": "时间戳显示秒",
            "Unread Digest on Return": "回到应用时的未读摘要",
            "Hide Stories Tray": "隐藏动态栏",
            "Hide My Story Prompt": "隐藏发布动态提示",
            "Hides the stories strip in chats and the story ring around avatars app-wide. Does not touch anyone's stories on the server.": "在聊天列表中隐藏动态栏，并隐藏全应用中头像周围的动态圆环。不会改动服务器上任何人的动态。",
            "Bookmarks": "书签",
            "Bookmark": "添加书签",
            "Delete this bookmark?": "删除此书签？",
            "No bookmarks yet. Add one from a message's context menu (“Bookmark”).": "还没有书签。在消息的长按菜单中选择「添加书签」即可添加。",
            "Quick Replies": "快捷回复",
            "Add Template": "添加模板",
            "Edit Template": "编辑模板",
            "New Template": "新建模板",
            "Delete Template": "删除模板",
            "Message text to insert": "要插入的消息文本",
            "e.g. Thanks": "例如：谢谢",
            "Insert a template while composing a message from the Quick Reply option in the text field's selection menu.": "编写消息时，从输入框选择菜单里的「快捷回复」插入模板。",
            "Contact Note": "联系人备注",
            "Only you can see this note": "只有你能看到这条备注",
            "e.g. work, family": "例如：工作、家人",
            "Comma-separated. Stored only on this device, never sent to Telegram or included in this person's profile.": "以逗号分隔。仅保存在这台设备上，绝不会发送给 Telegram，也不会加入此人的个人资料。",
            "Backup": "备份",
            "Export Backup": "导出备份",
            "Import Backup": "导入备份",
            "Passphrase": "口令",
            "Fallback code": "备用密码",
            "Backup restored.": "备份已恢复。",
            "Could not create the backup file.": "无法创建备份文件。",
            "Could not restore the backup. Check the passphrase and try again.": "无法恢复备份。请检查口令后重试。",
            "Enter a passphrase first.": "请先输入口令。",
            "Enter the backup's passphrase first.": "请先输入该备份的口令。",
            "Backs up quick-reply templates, bookmarks, contact notes and every other LuminaGram setting on this device. Importing replaces all current LuminaGram settings on this device.": "备份这台设备上的快捷回复模板、书签、联系人备注以及其他所有 LuminaGram 设置。导入会替换这台设备上当前的全部 LuminaGram 设置。",
            "Used to encrypt (export) or decrypt (import) the backup file. Not stored anywhere - re-enter it each time. If you lose it, the backup cannot be recovered.": "用于加密（导出）或解密（导入）备份文件。不会保存在任何地方——每次都需重新输入。一旦丢失，备份将无法恢复。",
            "Hide My Phone Number": "隐藏我的电话号码",
            "Show Registration Date": "显示注册日期",
            "Registration date": "注册日期",
            "These are local display and on-send options. Hiding your phone number and estimating a contact's registration date happen only on this device; photo metadata is stripped before a photo leaves your device.": "这些是本地显示和发送时的选项。隐藏你的电话号码、估算联系人的注册日期都只在这台设备上进行；照片元数据会在照片离开你的设备前被移除。",
            "Security Checkup": "账号安全体检",
            "Security Settings": "安全设置",
            "Checking…": "检查中…",
            "Checking your account security…": "正在检查你的账号安全…",
            "Your account security looks good.": "你的账号保护得不错。",
            "Two-Step Verification": "两步验证",
            "Recovery E-Mail": "救援邮箱",
            "Devices Signed In": "已登录的设备",
            "Active sessions": "活动会话",
            "Who Can Call Me": "谁可以给我打电话",
            "Who Can Add Me to Groups": "谁可以把我加入群组",
            "Who Can See My Phone Number": "谁可以看到我的电话号码",
            "Set": "已设置",
            "Not Set": "未设置",
            "Off": "未开启",
            "Hidden": "已隐藏",
            "Nobody": "没有人",
            "Everybody": "所有人",
            "My Contacts": "我的联系人",
            "A password (plus a recovery e-mail) is the single strongest protection against a stolen login code.": "设置密码（并加上救援邮箱）是抵御登录验证码被盗的最强防线。",
            "Review every device signed in to your account and end any you don't recognize.": "查看所有登录你账号的设备，并终止任何你不认识的。",
            "Read-only status of Two-Step Verification, recovery e-mail, privacy and active sessions, using Telegram's own settings screens.": "以只读方式显示两步验证、救援邮箱、隐私和活动会话的状态，使用 Telegram 自带的设置页面。",
            "Tap any row to open Telegram's own Privacy and Security settings.": "点按任意项，打开 Telegram 自带的隐私与安全设置。",
            "New Login Alerts": "新登录提醒",
            "New device signed in": "发现新登录",
            "Session terminated": "已终止该登录",
            "That was me": "是我",
            "Not me — Terminate": "不是我 — 立即终止",
            "Later": "以后再说",
            "A new device just signed in to your account.": "有一台新设备刚刚登录了你的账号。",
            "Turning on Two-Step Verification stops a repeat — a stolen login code alone won't be enough to sign in again.": "开启两步验证可防止重演——光靠被盗的登录验证码将无法再次登录。",
            "Login Code Guard": "登录验证码守卫",
            "Login Code Detected": "检测到登录验证码",
            "This message looks like it contains your Telegram login code. Telegram staff and real support will never ask you to send it. Send anyway?": "这条消息看起来包含你的 Telegram 登录验证码。Telegram 员工和真正的客服绝不会要你发送它。仍要发送吗？",
            "Scam Keyword Warning": "诈骗关键词警告",
            "Look-Alike Name Warning": "近似字名称警示",
            "Link Safety Check": "链接安全检查",
            "Check This Link": "检查此链接",
            "This is a shortened link — its real destination is hidden until you open it.": "这是一个短链接——真实目标地址在你打开前始终隐藏。",
            "This address uses look-alike international characters (punycode).": "此地址使用了近似的国际化字符（punycode）。",
            "This address mixes letters from different alphabets — a common trick to impersonate a trusted site.": "此地址混用了不同字母系统的字符——这是冒充可信网站的常见手法。",
            "Disguised File Guard": "文件伪装防护",
            "Suspicious File": "可疑文件",
            "Open Anyway": "仍然打开",
            "Android app (.apk)": "安卓应用（.apk）",
            "Windows program (.exe)": "Windows 程序（.exe）",
            "Windows installer (.msi)": "Windows 安装程序（.msi）",
            "Java program (.jar)": "Java 程序（.jar）",
            "shell script (.sh)": "Shell 脚本（.sh）",
            "native program (ELF)": "原生程序（ELF）",
            "native program (Mach-O)": "原生程序（Mach-O）",
            "Wallet Address Paste Guard": "钱包地址粘贴防护",
            "Verify Wallet Address": "核对钱包地址",
            "Secret Code": "秘密密码",
            "Lock": "上锁",
            "Unlock": "解锁",
            "Locked chats are unlocked with Face ID / passcode. This optional code is a fallback only. It is stored in this device's Keychain, never in Telegram and never synced. Leave empty to remove it.": "已上锁的对话用 Face ID／密码解锁。此可选密码仅作备用。它保存在这台设备的钥匙串中，绝不会存到 Telegram，也不会同步。留空即可移除。",
            "Set a chat-lock code in LuminaGram settings before locking a chat.": "锁定对话前，请先在 LuminaGram 设置中设置对话锁密码。",
            "Confirm Before Sending": "发送前确认",
            "Send Anyway": "仍然发送",
            "Save": "保存",
            "Cancel": "取消",
            "Open": "打开",
            "Paste": "粘贴",
            "OK": "确定",
            "Add Account": "添加账号",
        ],
        "zh-hant": [
            "LANGUAGES": "語言",
            "INCOMING MESSAGES": "收到的訊息",
            "OUTGOING MESSAGES": "傳送的訊息",
            "TRANSLATE MODE": "翻譯模式",
            "TRANSLATION PROVIDER": "翻譯服務商",
            "TRANSLATE BEFORE SEND": "傳送前翻譯",
            "TONE FOR THIS CHAT": "這個對話的語氣",
            "GLOSSARY": "不翻譯詞表",
            "IMAGE TEXT": "圖片文字",
            "EXPLAIN": "解釋一下",
            "VOICE-TO-TEXT": "語音轉文字",
            "VOICE LANGUAGE": "語音語言",
            "REVERSE VOICE (EXPERIMENTAL)": "反向語音（實驗性）",
            "MESSAGE": "訊息",
            "MESSAGE TEXT": "訊息內容",
            "SHORTCUT NAME": "快捷名稱",
            "TAGS": "標籤",
            "PRIVATE NOTE": "私密備註",
            "TEMPLATES": "範本",
            "FEATURES": "功能",
            "SCREENS": "頁面",
            "STORIES": "限時動態",
            "DISPLAY": "顯示",
            "MEDIA": "媒體",
            "PRIVACY": "隱私",
            "PRIVACY & DISGUISE": "隱私與偽裝",
            "ANTI-SCAM GUARDS": "防詐騙防護",
            "TWO-STEP VERIFICATION": "兩步驟驗證",
            "ACTIVE SESSIONS": "使用中的裝置",
            "CHAT LOCK": "對話上鎖",
            "BACKUP PASSPHRASE": "備份密碼",
            "Translation": "翻譯",
            "Privacy": "隱私",
            "Security": "安全",
            "Tools": "工具",
            "Voice & Media": "語音與媒體",
            "LuminaGram options are stored on this device only and are never synced to Telegram.": "LuminaGram 的選項只儲存在這台裝置上，絕不會同步到 Telegram。",
            "These options and everything else under LuminaGram are stored on this device only.": "這些選項以及 LuminaGram 下的其他一切都只儲存在這台裝置上。",
            "I read": "我閱讀",
            "I send": "我傳送",
            "Target": "目標語言",
            "Interface language": "介面語言",
            "auto = recipient's language": "自動 = 對方語言",
            "Only Translate What I Can't Read": "只翻譯我看不懂的",
            "Private Chats": "私聊",
            "Groups & Channels": "群組與頻道",
            "All Chats": "所有對話",
            "Manual (per-chat toggle)": "手動（逐對話開關）",
            "Show Original + Translation": "顯示原文＋譯文",
            "Fold Long Originals": "摺疊過長原文",
            "Base URL": "介面位址",
            "Model": "模型",
            "API key": "API 金鑰",
            "DeepL Key": "DeepL 金鑰",
            "LLM Key": "LLM 金鑰",
            "LLM (OpenAI-compatible)": "LLM（相容 OpenAI）",
            "Test Provider": "測試服務商",
            "The test translation failed. Check the provider's API key and settings.": "測試翻譯失敗。請檢查服務商的 API 金鑰和設定。",
            "DeepL and LLM keys are stored in the device Keychain, never synced to Telegram or LuminaGram. Base URL/Model/Prompt apply to the LLM provider only.": "DeepL 和 LLM 金鑰儲存在裝置的鑰匙圈中，絕不會同步到 Telegram 或 LuminaGram。介面位址／模型／提示詞僅適用於 LLM 服務商。",
            "Could not reach the configured LLM provider. Check the base URL in Translation settings.": "無法連接所設定的 LLM 服務商。請檢查翻譯設定中的介面位址。",
            "Translate Before Send": "傳送前翻譯",
            "Enabled for This Chat": "已為此對話啟用",
            "Chat Translation Settings": "對話翻譯設定",
            "Send Translation": "傳送翻譯",
            "Send Original": "傳送原文",
            "Send translation?": "傳送翻譯？",
            "Also needs to be turned on per chat: long-press any message in that chat and choose Chat Translation Settings.": "還需在每個對話中單獨開啟：長按該對話中的任意訊息，選擇「對話翻譯設定」。",
            "Also needs the global switch on: Settings → LuminaGram → Translation → Translate Before Send.": "還需在總開關處開啟：設定 → LuminaGram → 翻譯 → 傳送前翻譯。",
            "Custom": "自訂",
            "None": "無",
            "Client": "客戶",
            "Colleague": "同事",
            "Friend": "朋友",
            "Family": "家人",
            "Elder": "長輩",
            "Romantic interest": "曖昧對象",
            "Only the LLM provider can carry tone. DeepL collapses it onto formal/informal where supported; Google and Telegram ignore it.": "只有 LLM 服務商能傳達語氣。DeepL 在支援的語言上會壓縮為正式／非正式；Google 和 Telegram 會忽略語氣。",
            "e.g. \"my landlord\"": "例如：我的房東",
            "Glossary": "不翻譯詞表",
            "iPhone, Acme Corp — one term per line or comma-separated": "iPhone、Acme Corp — 每行一個詞或用逗號分隔",
            "Explain": "解釋一下",
            "Explain-a-Message": "解釋訊息",
            "Add an LLM API key on the Translation settings page to use Explain.": "請先在翻譯設定頁新增 LLM API 金鑰，才能使用「解釋一下」。",
            "Could not get an explanation. Check your LLM provider settings and try again.": "無法取得解釋。請檢查你的 LLM 服務商設定後再試一次。",
            "Translate Image": "翻譯圖中文字",
            "Show \"Translate Image\" action": "顯示「翻譯圖片」動作",
            "Uses Telegram's existing on-device Vision text recognition to translate text found in photos and screenshots, from the image viewer's menu.": "借助 Telegram 已有的裝置端 Vision 文字辨識，從圖片檢視器選單翻譯相片和截圖中的文字。",
            "Auto-transcribe in translated chats": "在翻譯的對話中自動轉錄",
            "Translate transcript automatically": "自動翻譯轉錄文字",
            "Transcribing…": "轉錄中…",
            "Transcription failed.": "轉錄失敗。",
            "No speech was recognized.": "未辨識到語音。",
            "On-device transcription isn't available for this language.": "此語言暫不支援裝置端轉錄。",
            "Speech recognition permission is required. Enable it in Settings.": "需要語音辨識權限。請在系統設定中開啟。",
            "Voice message isn't downloaded yet.": "語音訊息尚未下載。",
            "Couldn't read this voice message.": "無法讀取這則語音訊息。",
            "Reverse Voice": "反向語音",
            "Enable reverse voice": "啟用反向語音",
            "Send a Reverse Voice Message": "傳送反向語音訊息",
            "Send as Voice Message": "以語音訊息傳送",
            "Message": "訊息",
            "Type the message to speak…": "輸入要朗讀的訊息…",
            "Voice message sent.": "語音訊息已傳送。",
            "Couldn't create the voice message.": "無法產生語音訊息。",
            "en, ja, fr — one per line or comma-separated": "en、ja、fr — 每行一個或用逗號分隔",
            "BCP-47 language/voice code understood by AVSpeechSynthesisVoice.": "AVSpeechSynthesisVoice 可辨識的 BCP-47 語言／語音代碼。",
            "Spoken on-device with AVSpeechSynthesizer and sent as a real voice message. No cloud TTS, no voice cloning.": "使用 AVSpeechSynthesizer 在裝置上朗讀，並以真正的語音訊息傳送。不使用雲端 TTS，不做語音複製。",
            "e.g. en-US, zh-CN (leave empty to auto-detect)": "例如 en-US、zh-CN（留空自動偵測）",
            "Auto-pause video in background": "應用程式退到背景時暫停影片",
            "Keep original filename on save": "儲存時保留原始檔名",
            "Strip Photo Metadata": "移除相片中繼資料",
            "Save to \"LuminaGram\" album": "儲存到「LuminaGram」相簿",
            "Sticker Size": "貼圖大小",
            "Choose how large stickers render in chats.": "調整貼圖在聊天中的顯示大小。",
            "Small (75%)": "小（75%）",
            "Default (100%)": "預設（100%）",
            "Large (125%)": "大（125%）",
            "Precise Counts": "精確計數",
            "No 1.2K / 3.4M rounding": "不使用 1.2K／3.4M 縮寫",
            "Seconds in Timestamps": "時間戳顯示秒",
            "Unread Digest on Return": "回到應用時的未讀摘要",
            "Hide Stories Tray": "隱藏限時動態列",
            "Hide My Story Prompt": "隱藏發布限時動態提示",
            "Hides the stories strip in chats and the story ring around avatars app-wide. Does not touch anyone's stories on the server.": "在聊天列表中隱藏限時動態列，並隱藏全應用程式中頭像周圍的限時動態圓環。不會改動伺服器上任何人的限時動態。",
            "Bookmarks": "書籤",
            "Bookmark": "加入書籤",
            "Delete this bookmark?": "刪除此書籤？",
            "No bookmarks yet. Add one from a message's context menu (“Bookmark”).": "還沒有書籤。在訊息的長按選單中選擇「加入書籤」即可加入。",
            "Quick Replies": "快捷回覆",
            "Add Template": "新增範本",
            "Edit Template": "編輯範本",
            "New Template": "新增範本",
            "Delete Template": "刪除範本",
            "Message text to insert": "要插入的訊息內容",
            "e.g. Thanks": "例如：謝謝",
            "Insert a template while composing a message from the Quick Reply option in the text field's selection menu.": "編寫訊息時，從輸入框選取選單裡的「快捷回覆」插入範本。",
            "Contact Note": "聯絡人備註",
            "Only you can see this note": "只有你能看到這則備註",
            "e.g. work, family": "例如：工作、家人",
            "Comma-separated. Stored only on this device, never sent to Telegram or included in this person's profile.": "以逗號分隔。僅儲存在這台裝置上，絕不會傳送給 Telegram，也不會加入此人的個人資料。",
            "Backup": "備份",
            "Export Backup": "匯出備份",
            "Import Backup": "匯入備份",
            "Passphrase": "密碼",
            "Fallback code": "備用密碼",
            "Backup restored.": "備份已還原。",
            "Could not create the backup file.": "無法建立備份檔案。",
            "Could not restore the backup. Check the passphrase and try again.": "無法還原備份。請檢查密碼後再試一次。",
            "Enter a passphrase first.": "請先輸入密碼。",
            "Enter the backup's passphrase first.": "請先輸入該備份的密碼。",
            "Backs up quick-reply templates, bookmarks, contact notes and every other LuminaGram setting on this device. Importing replaces all current LuminaGram settings on this device.": "備份這台裝置上的快捷回覆範本、書籤、聯絡人備註以及其他所有 LuminaGram 設定。匯入會取代這台裝置上目前的全部 LuminaGram 設定。",
            "Used to encrypt (export) or decrypt (import) the backup file. Not stored anywhere - re-enter it each time. If you lose it, the backup cannot be recovered.": "用於加密（匯出）或解密（匯入）備份檔案。不會儲存在任何地方——每次都需重新輸入。一旦遺失，備份將無法還原。",
            "Hide My Phone Number": "隱藏我的電話號碼",
            "Show Registration Date": "顯示註冊日期",
            "Registration date": "註冊日期",
            "These are local display and on-send options. Hiding your phone number and estimating a contact's registration date happen only on this device; photo metadata is stripped before a photo leaves your device.": "這些是本地顯示和傳送時的選項。隱藏你的電話號碼、估算聯絡人的註冊日期都只在這台裝置上進行；相片中繼資料會在相片離開你的裝置前被移除。",
            "Security Checkup": "帳號安全體檢",
            "Security Settings": "安全設定",
            "Checking…": "檢查中…",
            "Checking your account security…": "正在檢查你的帳號安全…",
            "Your account security looks good.": "你的帳號保護得不錯。",
            "Two-Step Verification": "兩步驟驗證",
            "Recovery E-Mail": "救援信箱",
            "Devices Signed In": "已登入的裝置",
            "Active sessions": "使用中的裝置",
            "Who Can Call Me": "誰可以打電話給我",
            "Who Can Add Me to Groups": "誰可以把我加入群組",
            "Who Can See My Phone Number": "誰可以看到我的電話號碼",
            "Set": "已設定",
            "Not Set": "未設定",
            "Off": "未開啟",
            "Hidden": "已隱藏",
            "Nobody": "沒有人",
            "Everybody": "所有人",
            "My Contacts": "我的聯絡人",
            "A password (plus a recovery e-mail) is the single strongest protection against a stolen login code.": "設定密碼（並加上救援信箱）是抵禦登入驗證碼被盜的最強防線。",
            "Review every device signed in to your account and end any you don't recognize.": "查看所有登入你帳號的裝置，並終止任何你不認得的。",
            "Read-only status of Two-Step Verification, recovery e-mail, privacy and active sessions, using Telegram's own settings screens.": "以唯讀方式顯示兩步驟驗證、救援信箱、隱私和使用中裝置的狀態，使用 Telegram 內建的設定頁面。",
            "Tap any row to open Telegram's own Privacy and Security settings.": "點按任一項，開啟 Telegram 內建的隱私與安全設定。",
            "New Login Alerts": "新登入警示",
            "New device signed in": "偵測到新登入",
            "Session terminated": "已終止該登入",
            "That was me": "是我",
            "Not me — Terminate": "不是我 — 立即終止",
            "Later": "稍後再說",
            "A new device just signed in to your account.": "有一台新裝置剛剛登入了你的帳號。",
            "Turning on Two-Step Verification stops a repeat — a stolen login code alone won't be enough to sign in again.": "開啟兩步驟驗證可防止重演——光靠被盜的登入驗證碼將無法再次登入。",
            "Login Code Guard": "登入驗證碼守衛",
            "Login Code Detected": "偵測到登入驗證碼",
            "This message looks like it contains your Telegram login code. Telegram staff and real support will never ask you to send it. Send anyway?": "這則訊息看起來包含你的 Telegram 登入驗證碼。Telegram 員工和真正的客服絕不會要你傳送它。仍要傳送嗎？",
            "Scam Keyword Warning": "詐騙關鍵字警告",
            "Look-Alike Name Warning": "近似字名稱警示",
            "Link Safety Check": "連結安全檢查",
            "Check This Link": "檢查此連結",
            "This is a shortened link — its real destination is hidden until you open it.": "這是一個短連結——真實目標位址在你開啟前始終隱藏。",
            "This address uses look-alike international characters (punycode).": "此位址使用了近似的國際化字元（punycode）。",
            "This address mixes letters from different alphabets — a common trick to impersonate a trusted site.": "此位址混用了不同字母系統的字元——這是冒充可信網站的常見手法。",
            "Disguised File Guard": "檔案偽裝防護",
            "Suspicious File": "可疑檔案",
            "Open Anyway": "仍要開啟",
            "Android app (.apk)": "Android 應用程式（.apk）",
            "Windows program (.exe)": "Windows 程式（.exe）",
            "Windows installer (.msi)": "Windows 安裝程式（.msi）",
            "Java program (.jar)": "Java 程式（.jar）",
            "shell script (.sh)": "Shell 指令碼（.sh）",
            "native program (ELF)": "原生程式（ELF）",
            "native program (Mach-O)": "原生程式（Mach-O）",
            "Wallet Address Paste Guard": "錢包地址貼上防護",
            "Verify Wallet Address": "核對錢包地址",
            "Secret Code": "秘密密碼",
            "Lock": "上鎖",
            "Unlock": "解鎖",
            "Locked chats are unlocked with Face ID / passcode. This optional code is a fallback only. It is stored in this device's Keychain, never in Telegram and never synced. Leave empty to remove it.": "已上鎖的對話用 Face ID／密碼解鎖。此選填密碼僅作備用。它儲存在這台裝置的鑰匙圈中，絕不會存到 Telegram，也不會同步。留空即可移除。",
            "Set a chat-lock code in LuminaGram settings before locking a chat.": "鎖定對話前，請先在 LuminaGram 設定中設定對話鎖密碼。",
            "Confirm Before Sending": "傳送前確認",
            "Send Anyway": "仍要傳送",
            "Save": "儲存",
            "Cancel": "取消",
            "Open": "開啟",
            "Paste": "貼上",
            "OK": "確定",
            "Add Account": "新增帳號",
        ],
    ]
}
